[package]
name = "sc-reforged"
version = "0.1.0"
edition = "2024"

[dependencies]
shadow_company_tools = { path = "../shadow_company_tools" }

ahash = "0.8"
bevy_ecs = { version = "0.19", default-features = false }
bitflags = "2.13"
bytemuck = { version = "1.18", default-features = false, features = ["derive"] }
byteorder = { version = "1.5", default-features = false, features = ["std"] }
clap = { version = "4.5", features = ["derive"] }
generational-arena = "0.2"
glam = { version = "0.33", default-features = false, features = ["bytemuck", "std", "float-types", "integer-types"] }
image = { version = "0.25", default-features = false, features = ["bmp", "jpeg"] }
pathdiff = "0.2"
pcx = { version = "0.2", default-features = false }
pollster = { version = "1", default-features = false }
send_wrapper = "0.6.0"
smallvec = { version = "1.15.1", features = ["const_new"] }
strum = { version = "0.28", features = ["derive"] }
thiserror = { version = "2.0", default-features = false }
tracing = { version = "0.1", default-features = false, features = ["release_max_level_info", "max_level_debug"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["ansi", "fmt"] }
walkdir = { version = "2.5", default-features = false }
wgpu = { version = "30.0" }
winit = { version = "0.30" }

# Pinned for compatibility.
zune-jpeg = { version = "=0.5.5" }

[build-dependencies]
heck = "0.5"
naga = { version = "30.0", features = ["wgsl-out"] } # should match wgpu
naga_oil = { version = "0.23", default-features = false } # must depend on the same naga
prettyplease = "0.3"
quote = "1"
syn = "3.0"

[profile.dev.package.zune-jpeg]
opt-level = 3
