use ahash::HashSet;

use bevy_ecs::{component::Component, resource::Resource, schedule::ScheduleLabel};

use crate::{
    engine::{gizmos::GizmoVertex, input::InputState, storage::Handle},
    game::{
        model::Model,
        scenes::world::sim_world::{FreeCameraController, TopDownCameraController},
    },
};

#[derive(Clone, Debug, Eq, Hash, PartialEq, ScheduleLabel)]
pub struct InputSchedule;

#[derive(Clone, Debug, Eq, Hash, PartialEq, ScheduleLabel)]
pub struct UpdateSchedule;

/// Keep track of render resources generated by the [SimWorld].
#[derive(Default, Resource)]
pub struct PendingRenderStore {
    /// List of model handles that have to be prepared by the renderer.
    pub models: HashSet<Handle<Model>>,
}

/// A list of [GizmoVertex]s gathered during simulation for debug rendering.
#[derive(Default, Resource)]
pub struct GizmoVertices {
    pub vertices: Vec<GizmoVertex>,
}

/// Marker component to set the active camera.
#[derive(Component)]
pub struct ActiveCamera;

/// Wrapper for input state.
#[derive(Default, Resource)]
pub struct InputStateResource(pub InputState);

/// Wrapper for camera controllers.
#[derive(Component)]
pub enum CameraController {
    TopDown(TopDownCameraController),
    Free(FreeCameraController),
}
